#!/usr/bin/env python3
"""Recommend an active-learning method from observed learning curves.

ALDA fits a PALM curve to each method trajectory and ranks methods by the
estimated label budget required to reach a user-selected target score.  Its
primary input is one or more output directories generated by ``PALM.py``;
portable CSV input is also supported for use with other AL frameworks.

Required input columns: ``dataset``, ``method``, ``cumulative_budget``, and
``score``. Scores may be proportions (0--1) or percentages (0--100).
"""

from __future__ import annotations

import argparse
import csv
import json
import math
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import numpy as np
from scipy.optimize import curve_fit


EPS = 1e-8


@dataclass(frozen=True)
class PalmFit:
    a_max: float
    delta: float
    alpha: float
    beta: float
    rmse: float


def palm_model(x: np.ndarray, a_max: float, delta: float, alpha: float, beta: float) -> np.ndarray:
    """PALM learning curve evaluated at cumulative-label budgets ``x``."""
    inner = np.clip(x + alpha, EPS, None) ** beta
    return a_max * (1.0 - (1.0 - np.clip(delta, EPS, 1.0 - EPS)) ** inner)


def fit_palm(budgets: np.ndarray, scores: np.ndarray, maxfev: int = 20_000) -> PalmFit | None:
    """Fit PALM robustly using a small, deterministic multi-start search."""
    if len(budgets) < 4 or len(np.unique(budgets)) < 4:
        return None

    observed_max = float(np.max(scores))
    a_max_hi = max(100.0, observed_max * 1.25 + 1.0)
    bounds = (
        [observed_max, EPS, -float(np.max(budgets)), 0.05],
        [a_max_hi, 1.0 - EPS, float(np.max(budgets)) * 10.0 + 1.0, 10.0],
    )
    best: tuple[np.ndarray, float] | None = None
    for delta0 in (0.01, 0.05, 0.2):
        for alpha0 in (0.0, float(budgets[0])):
            for beta0 in (0.5, 1.0, 2.0):
                initial = [min(observed_max * 1.05, a_max_hi - EPS), delta0, alpha0, beta0]
                try:
                    params, _ = curve_fit(
                        palm_model,
                        budgets,
                        scores,
                        p0=initial,
                        bounds=bounds,
                        maxfev=maxfev,
                    )
                except (RuntimeError, ValueError, FloatingPointError):
                    continue
                rmse = float(np.sqrt(np.mean((scores - palm_model(budgets, *params)) ** 2)))
                if best is None or rmse < best[1]:
                    best = (params, rmse)
    if best is None:
        return None
    params, rmse = best
    return PalmFit(*(float(value) for value in params), rmse=rmse)


def budget_at_target(fit: PalmFit, target: float) -> float | None:
    """Return the estimated labels needed to reach ``target``, if reachable."""
    if target <= 0.0:
        return 0.0
    if target >= fit.a_max or not 0.0 < fit.delta < 1.0 or fit.beta <= 0.0:
        return None
    exponent = math.log(1.0 - target / fit.a_max) / math.log(1.0 - fit.delta)
    if exponent <= 0.0:
        return None
    budget = exponent ** (1.0 / fit.beta) - fit.alpha
    return max(0.0, float(budget))


def load_curves(path: Path) -> tuple[dict[tuple[str, str], tuple[np.ndarray, np.ndarray]], bool]:
    """Load and validate portable ALDA curve CSV data."""
    groups: dict[tuple[str, str], list[tuple[float, float]]] = defaultdict(list)
    with path.open(newline="") as handle:
        reader = csv.DictReader(handle)
        required = {"dataset", "method", "cumulative_budget", "score"}
        if not reader.fieldnames or not required.issubset(reader.fieldnames):
            raise ValueError(f"{path} must contain columns: {', '.join(sorted(required))}")
        for row in reader:
            groups[(row["dataset"], row["method"])].append(
                (float(row["cumulative_budget"]), float(row["score"]))
            )
    if not groups:
        raise ValueError(f"{path} contains no curve rows")
    is_fraction = max(score for values in groups.values() for _, score in values) <= 1.0
    curves = {}
    for key, values in groups.items():
        values.sort()
        budgets, scores = (np.asarray(value, dtype=float) for value in zip(*values))
        curves[key] = (budgets, scores * (100.0 if is_fraction else 1.0))
    return curves, is_fraction


def load_palm_outputs(paths: Iterable[Path]) -> dict[tuple[str, str], tuple[np.ndarray, np.ndarray]]:
    """Load averaged curves from one or more ``PALM.py --out_dir`` directories."""
    curves: dict[tuple[str, str], tuple[np.ndarray, np.ndarray]] = {}
    for path in paths:
        params_path = path / "palm_params.json"
        curve_path = path / "y_avg.npy"
        if not params_path.exists() or not curve_path.exists():
            raise FileNotFoundError(
                f"{path} must contain PALM outputs palm_params.json and y_avg.npy"
            )
        with params_path.open() as handle:
            metadata = json.load(handle)
        dataset = str(metadata["dataset"])
        method = str(metadata["method"])
        budget_size = metadata.get("budget_size")
        if budget_size is None or float(budget_size) <= 0:
            raise ValueError(
                f"{params_path} has no usable budget_size. Re-run PALM.py with the current release."
            )
        scores = np.asarray(np.load(curve_path), dtype=float)
        if scores.ndim != 1 or not len(scores):
            raise ValueError(f"{curve_path} must be a non-empty one-dimensional array")
        key = (dataset, method)
        if key in curves:
            raise ValueError(f"Duplicate PALM output for dataset={dataset!r}, method={method!r}")
        budgets = np.arange(1, len(scores) + 1, dtype=float) * float(budget_size)
        curves[key] = (budgets, scores)
    if not curves:
        raise ValueError("At least one PALM output directory is required")
    return curves


def write_rows(path: Path, fieldnames: Iterable[str], rows: Iterable[dict[str, object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def advise_curves(
    curves: dict[tuple[str, str], tuple[np.ndarray, np.ndarray]],
    output_dir: Path,
    target_percent: float,
    max_points: int | None,
) -> Path:
    fit_rows: list[dict[str, object]] = []
    advice_by_dataset: dict[str, list[dict[str, object]]] = defaultdict(list)

    for (dataset, method), (budgets, scores) in sorted(curves.items()):
        if max_points is not None:
            budgets, scores = budgets[:max_points], scores[:max_points]
        fit = fit_palm(budgets, scores)
        row: dict[str, object] = {
            "dataset": dataset,
            "method": method,
            "points_used": len(budgets),
            "observed_final_score_percent": float(scores[-1]),
            "fit_status": "ok" if fit else "too_few_points_or_fit_failed",
        }
        if fit:
            target_budget = budget_at_target(fit, target_percent)
            row.update({
                "a_max_percent": fit.a_max,
                "delta": fit.delta,
                "alpha": fit.alpha,
                "beta": fit.beta,
                "rmse": fit.rmse,
                "estimated_budget_at_target": target_budget if target_budget is not None else "",
            })
            advice_by_dataset[dataset].append(row)
        fit_rows.append(row)

    advice_rows: list[dict[str, object]] = []
    for dataset, candidates in sorted(advice_by_dataset.items()):
        reachable = [row for row in candidates if row["estimated_budget_at_target"] != ""]
        if reachable:
            winner = min(reachable, key=lambda row: float(row["estimated_budget_at_target"]))
            reason = "lowest_estimated_budget_at_target"
        else:
            winner = max(candidates, key=lambda row: float(row["a_max_percent"]))
            reason = "target_unreachable_choose_highest_estimated_ceiling"
        advice_rows.append({
            "dataset": dataset,
            "target_score_percent": target_percent,
            "recommended_method": winner["method"],
            "selection_reason": reason,
            "estimated_budget_at_target": winner["estimated_budget_at_target"],
        })

    write_rows(
        output_dir / "alda_fits.csv",
        ["dataset", "method", "points_used", "observed_final_score_percent", "fit_status",
         "a_max_percent", "delta", "alpha", "beta", "rmse", "estimated_budget_at_target"],
        fit_rows,
    )
    advice_path = output_dir / "alda_advice.csv"
    write_rows(
        advice_path,
        ["dataset", "target_score_percent", "recommended_method", "selection_reason",
         "estimated_budget_at_target"],
        advice_rows,
    )
    return advice_path


def advise(input_path: Path, output_dir: Path, target: float, max_points: int | None) -> Path:
    """Advise from the portable CSV interface."""
    curves, fraction_scores = load_curves(input_path)
    return advise_curves(curves, output_dir, target * 100.0 if fraction_scores else target, max_points)


def advise_from_palm_outputs(
    paths: Iterable[Path], output_dir: Path, target: float, max_points: int | None
) -> Path:
    """Advise directly from the outputs created by one PALM run per method."""
    return advise_curves(load_palm_outputs(paths), output_dir, target, max_points)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="ALDA: advise from PALM learning-curve outputs.")
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--input", type=Path, help="CSV with dataset, method, cumulative_budget, score.")
    source.add_argument(
        "--palm-output", type=Path, nargs="+", metavar="DIR",
        help="One or more directories produced by PALM.py --out_dir (recommended).",
    )
    parser.add_argument("--output-dir", required=True, type=Path, help="Directory for ALDA CSV outputs.")
    parser.add_argument("--target", required=True, type=float, help="Target score (same scale as input: 0--1 or 0--100).")
    parser.add_argument("--max-points", type=int, default=None, help="Use only this many early points from every curve.")
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    if args.palm_output:
        advice = advise_from_palm_outputs(args.palm_output, args.output_dir, args.target, args.max_points)
    else:
        advice = advise(args.input, args.output_dir, args.target, args.max_points)
    print(f"Wrote ALDA recommendation: {advice}")
